FROM node:16

ENV MONGODB_CONNECTION_PROTOCOL mongodb+srv
ENV MONGODB_DB_NAME Cluster0
ENV MONGODB_CLUSTER_ADDRESS cluster0.nw2ityb.mongodb.net
ENV MONGODB_USERNAME admin
ENV MONGODB_PASSWORD IpTEWDSJTbC0Ea3B

WORKDIR /app

COPY package*.json .

RUN npm install

COPY . .

CMD ["npm", "start"]
